// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "InsertGuid.0124c4ba-1c2a-4a32-98c7-39b0c9e2ba3c";
        public const string Name = "InsertGuid";
        public const string Description = @"Inserts a guid into the text editor in a simple click";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Даниил Спиридонов";
        public const string Tags = "";
    }
}
